// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmo6dPzN4M71UFnuMOpz23KoKUN4WnIrg',
    appId: '1:970996524919:web:f5c058b7d37fb4ec072372',
    messagingSenderId: '970996524919',
    projectId: 'eventhub-d5812',
    authDomain: 'eventhub-d5812.firebaseapp.com',
    storageBucket: 'eventhub-d5812.firebasestorage.app',
    measurementId: 'G-ZGEDGY9E85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZi_EzkVZpk51a0Si77kRTv9jAGB_w-64',
    appId: '1:970996524919:android:bbaa4a32489bcdd7072372',
    messagingSenderId: '970996524919',
    projectId: 'eventhub-d5812',
    storageBucket: 'eventhub-d5812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrU-Ldpx1XGfxkwTcrpNQtZRZycO08paY',
    appId: '1:970996524919:ios:7b78d7e919d7d9aa072372',
    messagingSenderId: '970996524919',
    projectId: 'eventhub-d5812',
    storageBucket: 'eventhub-d5812.firebasestorage.app',
    iosBundleId: 'com.eventhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrU-Ldpx1XGfxkwTcrpNQtZRZycO08paY',
    appId: '1:970996524919:ios:7b78d7e919d7d9aa072372',
    messagingSenderId: '970996524919',
    projectId: 'eventhub-d5812',
    storageBucket: 'eventhub-d5812.firebasestorage.app',
    iosBundleId: 'com.eventhub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmo6dPzN4M71UFnuMOpz23KoKUN4WnIrg',
    appId: '1:970996524919:web:a750fc3705ae05f3072372',
    messagingSenderId: '970996524919',
    projectId: 'eventhub-d5812',
    authDomain: 'eventhub-d5812.firebaseapp.com',
    storageBucket: 'eventhub-d5812.firebasestorage.app',
    measurementId: 'G-D27WX1BQFP',
  );
}
